# Fedora base image
FROM fedora:latest

# Avoid warnings by switching to noninteractive for the build process
ENV DEBIAN_FRONTEND=noninteractive

ENV USER=root

# Install LXDE, VNC server, dbus-x11, xfonts-base, and other necessary packages
RUN dnf update -y && dnf install -y \
    @lxde-desktop \
    tigervnc-server \
    dbus-x11 \
    xorg-x11-fonts-Type1 \
    xorg-x11-fonts-misc \
    dnf-plugins-core \
    curl \
    glibc-locale-sourc \
    glibc-langpack-en \
    wget \
    figlet \
    && dnf clean all

# Add AnyDesk
RUN wget https://download.anydesk.com/linux/anydesk-6.3.2-1.el8.x86_64.rpm \
    && dnf install -y ./anydesk-6.3.2-1.el8.x86_64.rpm \
    && rm -f anydesk_6.3.2-1_x86_64.rpm

# Setup VNC server
RUN mkdir /root/.vnc \
    && echo "123" | vncpasswd -f > /root/.vnc/passwd \
    && chmod 600 /root/.vnc/passwd

# Create an .Xauthority file
RUN touch /root/.Xauthority

# Set display resolution (change as needed)
ENV RESOLUTION=1920x1080

# Expose VNC port
EXPOSE 5903

# Set the working directory in the container
WORKDIR /app

# Copy a script to start the VNC server
COPY start-vnc.sh start-vnc.sh
RUN chmod +x start-vnc.sh

# List the contents of the /app directory
RUN ls -a /app

# Configure the hostname and shell prompt
RUN echo 'export PS1="\\u@\\h: \\[\\033[01;34m\\]\\w\\[\\033[00m\\]$ "' >> /root/.bashrc && \
    echo 'figlet mgodoyd' >> /root/.bashrc

# Start the VNC server by default
CMD ["./start-vnc.sh"]
